services:
  api:
    build: .
    command: uvicorn sync_service.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SYNC_SERVICE_REDIS_URL=${SYNC_SERVICE_REDIS_URL:-redis://redis:6379/0}
      - SYNC_SERVICE_DATABASE_URL=${SYNC_SERVICE_DATABASE_URL:-sqlite:////app/data/sync_service.db}
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
